apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: infra-drupal-tls
    namespace: infra-drupal
spec:
    secretName: infra-drupal-tls
    issuerRef:
        name: ca-issuer
        kind: ClusterIssuer
    commonName: infra-drupal.almacg.com